# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import train_test_split

In [ ]:
#Feature Selection
data = pd.read_csv('bank_data.csv')
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values


In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
x[:, 2] = l.fit_transform(x[:, 2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
c = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(c.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=100)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [ ]:
model = Sequential()
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=50)

Epoch 1/50
250/250 [==============================] - 0s 1ms/step - loss: 0.5528 - accuracy: 0.7864
Epoch 2/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4738 - accuracy: 0.7969
Epoch 3/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4500 - accuracy: 0.7969
Epoch 4/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4369 - accuracy: 0.7969
Epoch 5/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4304 - accuracy: 0.7969
Epoch 6/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4266 - accuracy: 0.7969
Epoch 7/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4236 - accuracy: 0.7969
Epoch 8/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4213 - accuracy: 0.7969
Epoch 9/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4194 - accuracy: 0.8009
Epoch 10/50
250/250 [==============================] - 0s 1ms/step - loss: 0.4176 - accuracy: 0.8192

In [ ]:
#Geography: Germany
#Credit Score: 500
#Gender: Male
#Age: 30
#Tenure: 3 years
#Balance: $50000
#Number of Products:1
#Credit Card:Yes
#Salary:$60000
#Should we say goodbye to this Bank Customer?
print(model.predict(sc.transform([[0,1,0,850,0,43,2,125510,1,1,1,79084]]))>0.5)

[[ True]]


In [ ]:
print(model.predict(sc.transform([[1,0,0,635,0,35,7,0,2,1,1,65951]]))>0.5)

[[False]]


In [ ]:
y_predict = model.predict(x_test)
y_predict = (y_predict > 0.5)
print(np.concatenate((y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predict)
print(cm)

[[1526   62]
 [ 223  189]]


In [ ]:
accuracy_score(y_test, y_predict)

0.8575